### ISSUE TITLE
How to convert the value of tick to the time of the game ?

### ISSUE THREAD

**Issue by jacobxy** [ValveSoftware/csgo-demoinfo#11]
When I output the message of "CNETMsg_Tick" , I get the result like this: 
---- CNETMsg_Tick (12 bytes) -----------------
tick: 62278
host_computationtime: 3190
host_computationtime_std_deviation: 581
host_framestarttime_std_deviation: 13

So, how to convert the value of tick to the time of the game ?

**Comment by Traderain** [comment]
Multiply it by 0.015

**Comment by bugdone** [comment]
Actually multiply by `1/tickrate`. You can get the tickrate of the demo from the ServerInfo message.
