### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by ca1ek** [ValveSoftware/csgo-demoinfo#2]
This would be quite cool tool for third party hosting/matchmaking providers, letting them show stats of matches on web pages, track player performance, and would give them more data to work with when making their own matchmaking implementations.

However, most of these use cases are excluded by lack of instructions for building this tool on Linux.

I'm going to make a fork and take a look, but I have low experience with C++ so I can't make any promises.

**Comment by MikeLund** [comment]
To be frank, if one does not know how to build a C++ project on Linux, they are unfortunately most likely outside of the scope of this project.

In addition, with websites, you could most likely be using something a bit more premade, such as node-csgo instead, to parse demo files. Hope that helps.

**Comment by ca1ek** [comment]
Whoa, node-csgo is cool.

It's still Node though.

**Comment by saul** [comment]
There's also my own package saul/demoinfo that will parse CSGO demos.

**Comment by saul** [comment]
To answer your question, if this fork doesn't build correctly, I know that [csgo-data/demoinfogo-linux](https://github.com/csgo-data/demoinfogo-linux) builds and runs on Mac and Linux.

**Comment by ca1ek** [comment]
csgo-data/demoinfogo-linux is just what I've been searching for. Thanks.
