### ISSUE TITLE
missing round_end

### ISSUE THREAD

**Issue by econoraptor** [ValveSoftware/csgo-demoinfo#20]
Some demos have missing round_end events.  round_officially_ended seems to always trigger though.  Here's a demo where it happens multiple times: https://www.hltv.org/download/demo/28964

**Comment by jonasfs** [comment]
I noticed this too, and not while parsing, but watching normally through
the game client. I'm not sure, but I think this is an issue caused by
server plugins used by the tournament organizers. If thats indeed the case,
there's nothing we can do, except finding the round end through other means.

**Comment by bugdone** [comment]
This happens on Valve's MM servers too. And it's not only round_end events missing, but could be any event (eg kills, etc).

**Comment by 0BuRner** [comment]
Probably because on Valve servers GoTV relay isnt on the same host as the game server. Since UDP is used, some packets may be missing.
