### ISSUE TITLE
New UI can't display Chinese

### ISSUE THREAD

**Issue by RyuueikenLiu** [ValveSoftware/csgo-demoinfo#30]
The old UI can display Chinese,but the new one can't display Chinese even if I add '-language schinese'as a Startup item.

Could you solve the problem?
I use LINUX.
![screenshot_20180905_212233](https://user-images.githubusercontent.com/43361620/45687151-8b2d2600-bb80-11e8-9037-6bdb08fd50af.png)

**Comment by kisak-valve** [comment]
Hello @RyuueikenLiu, this issue is being tracked at https://github.com/ValveSoftware/csgo-osx-linux/issues/1730. Please use the csgo-osx-linux issue tracker for issues with the CS:GO game client.

Closing as a duplicate.
