### ISSUE TITLE
Patrol ban CSGO

### ISSUE THREAD

**Issue by a-korzhov** [ValveSoftware/csgo-demoinfo#39]
I have got patrol ban in CSGO.
I have some questions about it. Could I have info about some topics:
1. demo of the match, for which I have been banned
2. the results of patrol decisions and what ranks/stats/hours have those patrol players.
3. In the profile I have been adding Steam profile links of cheaters I played with, could it be a trigger for ban? 
4. During last games I always played with cheaters, but earlier it was not often, could it be a trigger for ban?

I ask these, because I am sure I am banned for a mistake.
My Steam profile: https://steamcommunity.com/id/iamnotdotaplayeranymorerofl/
My inventory contains expensive skins. More than 700$ charged on account.
Faceit account was also active, as I were playing not only matchmaking, but Faceit also.
Yes, I were often toxic, because of cheaters.  I were ruining game when I play with cheaters in team, but do I deserve ban for that? Yes, I would agree for: ban chat/temporal ban/etc, but not ban forever...
Steam Supports ignore all of my questions, they only answer with useless template messages.
All I've used during CSGO runnig - Faceit Anticheat, Razer Central, HyperX NGENUITY, Lightshot app.

I really hope to get clarfication about this ban.

Thank you in advance.

**Comment by kisak-valve** [comment]
Hello @a-korzhov, sorry, but account issues including bans are not handled on Github.
